api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns=[
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:pk>/', views.getSingleProject),
    path('projects/<str:pk>/vote/', views.projectVote),

    path('remove-tag/', views.removeTag),


]

users/urls.py
from django.urls import path
from . import views
from .views import *

# app_name='users'

urlpatterns =[

    path('login/', LoginUserView.as_view(), name="login-user"),
    path('logout/', LogoutUserView.as_view(), name="logout-user"),
    
    path('register/', RegisterUserView.as_view(), name="register-user"),
    path('activate/<uidb64>/<token>/', VerificationView.as_view(), name="activate"),
    path('activation-successful/', ActivationSuccessfulView.as_view(), name="activation-successful"),
    
    path('', ProfilesView.as_view(), name="profiles"),
    
    path('user/<str:pk>/', UserProfileView.as_view(), name="user-profile"),
    path('account/', UserAccountView.as_view(), name="account"),
    path('account/paginated-user-projects/', PaginatedUserProjectsView.as_view(), name="paginated-user-projects"),
    path('edit-account/', EditAccountView.as_view(), name="edit-account"),

    
    path('create-skill/', CreateSkillView.as_view(), name="create-skill"),
    path('update-skill/<str:pk>/', UpdateSkillView.as_view(), name="update-skill"),
    path('delete-skill/<str:pk>/', DeleteSkillView.as_view(), name="delete-skill"),

    
    path('inbox/', InboxView.as_view(), name="inbox"),
    path('message/<str:pk>/', ViewMessageView.as_view(), name="view-message"),
    path('inbox/paginated-inbox/', PaginatedInboxView.as_view(), name="paginated-inbox"),
    path('create-message/<str:pk>', CreateMessageView.as_view(), name="create-message"),
    path('delete-message/<str:pk>/', DeleteMessageView.as_view(), name="delete-message"),

    path('filtered-profiles/', FilteredProfilesView.as_view(), name="filtered-profiles"),

]

projects/models.py
from django.db import models
import uuid
from django.urls import reverse
from users.models import Profile





class Category(models.Model):
    CATEGORY_VALUE=(
        ('Software Development','development'),
        ('Data Science','datasci') ,
        ('Network Management','network'),
        ('System Administration','sysadm'),
        ('Other','other')
        
    )
    name = models.CharField(max_length=200,choices=CATEGORY_VALUE)
    slug = models.SlugField(max_length=200, unique=True)
    

    class Meta:
        ordering=('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('projects-by-category', args=[self.slug])




class Project(models.Model):
    
    owner=models.ForeignKey(Profile, null=True,blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    image=models.ImageField(null=True, blank=True, upload_to='project-images/',default="project-images/default.jpg")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tag=models.ManyToManyField('Tag', blank=True)
    total_votes=models.IntegerField(default=0, null=True, blank=True)
    vote_ratio=models.IntegerField(default=0, null=True, blank=True)
    category=models.ForeignKey('Category',related_name='categories' ,blank=False, on_delete=models.CASCADE)
    

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, 
        unique=True, primary_key=True, editable=False)

    def __str__(self): 
        return self.title

    class Meta:
        ordering=['-vote_ratio', '-total_votes','title']

    @property
    def imageUrl(self):
        try:
            url=self.image.url
        except:
            url='/images/project-images/default.jpg'
        return url

    @property
    def reviewers(self):
        queryset=self.review_set.all().values_list('owner__id', flat=True)
        return queryset

    @property
    def getVoteStats(self):
        reviews=self.review_set.all()
        upVotes=reviews.filter(value='up').count()
        totalVotes=reviews.count()
        ratio=(upVotes/totalVotes)*100

        self.total_votes=totalVotes
        self.vote_ratio=ratio
        self.save()


class Review(models.Model):
    VOTE_VALUE=(
        ('up', 'Thumb Up'),
        ('down', 'Thumb down')
        
    )
    owner=models.ForeignKey(Profile, on_delete=models.CASCADE,null=True)
    project=models.ForeignKey(Project, on_delete=models.CASCADE)
    body=models.TextField(null=True,blank=True)
    value=models.CharField(max_length=200, choices=VOTE_VALUE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, 
        unique=True, primary_key=True, editable=False)

    class Meta:
        unique_together=[['owner', 'project']]

    def __str__(self):
        return self.value


class Tag(models.Model):
    name=models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, 
        unique=True, primary_key=True, editable=False)
    
    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

# Create your models here.

class Profile(models.Model):
    EXPERIENCE_VALUE=(
        ('0-2 years', '0-2 years'),
        ('2-4 years', '2-4 years'),
        ('4+ years', '4+ years')
        
    )
    user=models.OneToOneField(User,on_delete=models.CASCADE, null=True,blank=True)
    name=models.CharField(max_length=200,null=True,blank=True)
    email=models.EmailField(max_length=500, null=True,blank=True)
    username=models.CharField(max_length=200,null=True,blank=True)
    location=models.CharField(max_length=200,null=True,blank=True)
    intro=models.CharField(max_length=200,null=True,blank=True)
    bio=models.TextField(null=True,blank=True)
    experience=models.CharField(max_length=200, choices=EXPERIENCE_VALUE,default="0-2 years")
    profile_image=models.ImageField(null=True, blank=True, upload_to='profile-images/', default='profile-images/user-default.png')
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, 
        unique=True, primary_key=True, editable=False)


    def __str__(self):
        return str(self.username)


    class Meta:
        ordering=['created']

    
    @property
    def imageUrl(self):
        try:
            url=self.profile_image.url
        except:
            url='/images/profile-images/user-default.png'
        return url


class Social(models.Model):
    owner=models.ForeignKey(Profile,on_delete=models.CASCADE, null=True, blank=True)
    social_github=models.CharField(max_length=200,null=True,blank=True)
    social_twitter=models.CharField(max_length=200,null=True,blank=True)
    social_linkedin=models.CharField(max_length=200,null=True,blank=True)
    social_website=models.CharField(max_length=200,null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, 
        unique=True, primary_key=True, editable=False)


    def __str__(self):
        return str(self.owner)

        
class Skill(models.Model):
    owner=models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name=models.CharField(max_length=200, null=True, blank=True)
    description=models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, 
        unique=True, primary_key=True, editable=False)


    def __str__(self):
        return str(self.name)



class Message(models.Model):
    sender=models.ForeignKey(Profile, on_delete=models.SET_NULL,null=True,blank=True)
    recipient=models.ForeignKey(Profile,on_delete=models.SET_NULL,null=True,blank=True, related_name="messages")
    name=models.CharField(max_length=200,null=False,blank=False)
    email=models.EmailField(max_length=500,null=True,blank=True)
    subject=models.CharField(max_length=200,blank=True)
    body=models.TextField()
    is_read=models.BooleanField(default=False,null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, 
        unique=True, primary_key=True, editable=False)


    def __str__(self):
        if self.subject:
            return self.subject
        else:
            return self.name

    class Meta:
        ordering=['is_read','-created']

users/forms.py
from django.forms import ModelForm,CharField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Social,Skill,Message
from django.core.validators import RegexValidator

class CustomUserCreationForm(UserCreationForm):
  
    class Meta:
        model=User
        fields=['first_name', 'email','username','password1','password2']
        labels={
            'first_name':'Name',
        }



    def __init__(self, *args,**kwargs):
        super(CustomUserCreationForm, self).__init__(*args,**kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True



        for name,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})



class ProfileForm(ModelForm):
    class Meta:
        model= Profile
        fields= ['name','email','username','location',
        'bio','experience','intro','profile_image']


    name = CharField(
        max_length=200,
        required=True,
        validators=[
           RegexValidator(
                regex=r'^[a-zA-Z\s\'\-]*$',
                message='Only alphabetic characters,- and \' are allowed for the name field.',
                code='invalid_name'
            ),
        ]
    )

    location = CharField(
        max_length=200,
        required=True,
        validators=[
           RegexValidator(
                regex=r'^[a-zA-Z\s\'\-]*$',
                message='Only alphabetic characters,- and \' are allowed for the location field.',
                code='invalid_location'
            ),
        ]
    )


    def __init__(self, *args,**kwargs):
        super(ProfileForm, self).__init__(*args,**kwargs)
        self.fields['email'].required = True
        self.fields['name'].required = True

        for name,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})



class ProfileSocialForm(ModelForm):
    class Meta:
        model= Social
        fields= ['social_github','social_twitter','social_linkedin','social_website']


    def __init__(self, *args,**kwargs):
        super(ProfileSocialForm, self).__init__(*args,**kwargs)

        for name,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})



class SkillForm(ModelForm):
    class Meta:
        model= Skill
        fields= '__all__'
        exclude=['owner']


    def __init__(self, *args,**kwargs):
        super(SkillForm, self).__init__(*args,**kwargs)
        self.fields['name'].required = True
        

        for name,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})



class MessageForm(ModelForm):


    class Meta:
        model=Message
        fields=['email','subject','body']

        
    def __init__(self, *args,**kwargs):
        super(MessageForm, self).__init__(*args,**kwargs)
        self.fields['email'].required = True
        self.fields['subject'].required = True
        

        for name,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})



class GuestMessageForm(ModelForm):

    class Meta:
        model=Message
        fields=['name','email','subject','body']

     
    name = CharField(
        max_length=200,
        required=True,
        validators=[
           RegexValidator(
                regex=r'^[a-zA-Z\s\'\-]*$',
                message='Only alphabetic characters,- and \' are allowed for the name field.',
                code='invalid_guest_message_form_name'
            ),
        ]
    )

    def __init__(self, *args,**kwargs):
        super(GuestMessageForm, self).__init__(*args,**kwargs)
        self.fields['name'].required = True
        self.fields['email'].required = True
        self.fields['subject'].required = True
        

        for name,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

users/templates/users/account.html
{% extends 'main.html' %}

{% block content %}

  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{profile.imageUrl}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.intro}}</p>
              <p class="dev__title">Based in {{profile.location}}</p>
              <p class="dev__location">Experience: {{profile.experience}}</p>
              <ul class="dev__social">
                {% if social.social_github %}  
                <li>
                  <a title="Github" href="{{social.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
                {% if social.social_twitter %} 
                <li>
                  <a title="Twitter" href="{{social.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}
                {% if social.social_linkedin %} 
                <li>
                  <a title="LinkedIn" href="{{social.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}
                {% if social.social_website %} 
                <li>
                  <a title="Personal Website" href="{{social.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
             
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">{{profile.bio}}</p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {% for skill in skills %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{skill.name}}</h4>
                <p>
                  {{skill.description}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skill' skill.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="im im-plus"></i> Add Project</a>
          </div>
          <div id="userProjectsContainer">
          <table class="settings__table">
            {% for pr in projects %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'project' pr.id %}"><img src="{{pr.imageUrl}}" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'project' pr.id %}">{{pr.title}}</a>
                <p>{{pr.description|slice:"150"}}</p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' pr.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' pr.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
            
          </table>
          {% include 'pagination.html' with queryset=projects custom_range=custom_range %}
        </div>
        </div>
      </div>
    </div>
  </main>

  <script type="text/javascript" src="/static/js/account.js"></script>

  {% endblock content %}

users/templates/users/activation-successful.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

<main class="inbox my-xl">
    <div class="content-box">
      <h4>Please activate your account by clicking the activation link sent to the email you have provided in order to proceed!</h4>
    </div>
</main>

{% endblock content %}

users/templates/users/filtered-profiles.html
<section class="devlist">
 
    <div class="container">
      <div class="grid grid--three">
        {% if not profiles %}
        <h5>No professionals found</h5>
        {% else %}
        {% for pr in profiles %}
        <div class="column card">
          <div class="dev">
            <a href="{% url 'user-profile' pr.id %}" class="card__body">
              <div class="dev__profile">
                <img class="avatar avatar--md" src="{{pr.imageUrl}}" alt="image" />
                <div class="dev__meta">
                  <h3>{{pr.name}}</h3>
                  <h5>{{pr.intro|slice:"60"}}</h5>
                  <h5>Experience: {{pr.experience}}</h5>
                </div>
              </div>
              <p class="dev__info">{{pr.bio|slice:"150"}}</p>
              <div class="dev__skills">
                {% for skill in pr.skill_set.all|slice:"5" %}
                <span class="tag tag--pill tag--main">
                  <small>{{skill}}</small>
                </span>
                {% endfor %}
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
        {% endif %}
      </div>
    </div>
  </section>

  {% include 'pagination.html' with queryset=profiles custom_range=custom_range %}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}


  <main class="inbox my-xl">
    <div id="inboxContainer">
    
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{unreadCount }}</span>)</h3>
      <h6>Total messages: {{totalMessages}}</h6>
      <ul class="messages">
        {% for message in messageRequests %}
        {% if message.is_read == False %}
        <li class="message message--unread">
        {% else %}
        <li class="message">
        {% endif %}
        
        <div class="cart-row product-item">
          <div style="flex: 2;"><a href="{% url 'view-message' message.id %}"><span class="message__author">{{message.name}}</span>  </a></div>
          <div style="flex: 2;"><a href="{% url 'view-message' message.id %}"><span class="message__author">{{message.subject}}</span>  </a></div>
          <div style="flex: 2;"><a href="{% url 'view-message' message.id %}"><span class="message__author">{{message.created}}</span>  </a></div>

          
        
          <div style="flex: a; ">
            <a href="{% url 'delete-message' message.id %}?next=/inbox" id="delete-button" data-index={{message.id}} data-action="delete" 
            style="float: right; margin: 5px; background-color:rgb(199, 10, 10); color: white;"
            class="btn remove-cart-item">Delete </a>
          </div> 
      </div>
            
       </li>
        {% endfor %}
      </ul>
    </div>
  
  {% include 'pagination.html' with queryset=messageRequests custom_range=custom_range %}
</div>
</main>

<script type="text/javascript" src="/static/js/inbox.js"></script>


  {% endblock content %}

users/templates/users/login-register.html
{% extends 'main.html' %}

{% load static %}

{% block content %}

{% if page == "register" %}

<div style="margin-top:100px;" class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Register</h3>
        <p>Create a new account</p>
      </div>

      <form method="POST" action="{% url 'register-user' %}" class="form auth__form">
        {% csrf_token %}

        {% for field in form %}
         <!-- Input:Text -->
         <div class="form__field">
            <label for="formInput#text">{{field.label}}: </label>
            {{field}}

            {% for error in field.errors %}
            <p style="color:red;">{{error}}</p>
            {% endfor %}

          </div> 
        {% endfor %}
       
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
        </div>
      </form>
      <div class="auth__alternative">
        <p>Already have an Account?</p>
        <a href="{% url 'login-user' %}">Log In</a>
      </div>
    </div>
  </div>

{% else %}

<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Account Login</h3>
        <p>Hello, Welcome Back!</p>
      </div>

      <form action="" method="POST" class="form auth__form">
        {% csrf_token %}
        <!-- Input:Username -->
        <div class="form__field">
          <label for="formInput#text">Username: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="username"
            placeholder="Enter your username..."
          />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="Enter your password"/>
            
          
        </div>
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
          <a href="{% url 'reset_password' %}">Forget Password?</a>
        </div>
      </form>
      <div class="auth__alternative">
        <p>Don’t have an Account?</p>
        <a href="{% url 'register-user' %}">Sign Up</a>
      </div>
    </div>
  </div>
{% endif %}

{% endblock content %}

users/templates/users/message-form.html
{% extends 'main.html' %}

{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'user-profile' recipientId %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                
                {% if request.user.is_authenticated == False %}
                <div class="form__field">
                    <label for="formInput#text">{{form.name.label}}: </label>
                    {{form.name}}
                </div>
                {% endif %}

                <div class="form__field">
                    <label for="formInput#text">{{form.email.label}}: </label>
                    {{form.email}}
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{form.subject.label}}: </label>
                    {{form.subject}}
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{form.body.label}}: </label>
                    {{form.body}}
                </div>
                
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Send"/>
                
            </form>
        </div>
    </div>
</main>

{% endblock content %}

users/templates/users/profiles.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>PROFESSIONALS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form id="searchForm" class="form" action="{% url 'profiles' %}" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Professionals </label>
              <input class="input input--text" id="searchValue" type="text" name="search_query"
               value="{{search_query}}" placeholder="Search professionals name, skillset..." />
            </div>

            <button id="searchBtn" class="btn btn--sub btn--lg" >Search</button>
            
          </form>
        </div>
        <div>
          
        </div>
      </div>
    </section>
    <!-- Search Result: ProfessionalsList -->
    <div id="profilesContainer">
    <section class="devlist">
    
      <div class="container">
        <div class="grid grid--three">
        {% if not profiles %}
        <h5>No professionals found</h5>
        {% else %}
          {% for pr in profiles %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'user-profile' pr.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{pr.imageUrl}}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{pr.name}}</h3>
                    <h5>{{pr.intro|slice:"60"}}</h5>
                    <h5>Experience: {{pr.experience}}</h5>
                  </div>
                </div>
                <p class="dev__info">{{pr.bio|slice:"150"}}</p>
                <div class="dev__skills">
                  {% for skill in pr.skill_set.all|slice:"5" %}
                  <span class="tag tag--pill tag--main">
                    <small>{{skill}}</small>
                  </span>
                  {% endfor %}
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
          {% endif %}
        </div>
      </div>
    </section>

    {% include 'pagination.html' with queryset=profiles custom_range=custom_range %}
  </div>
  </main>

  <script type="text/javascript" src="/static/js/profiles.js"></script>

{% endblock content %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}

 <!-- Main Section -->
 <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.imageUrl}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.intro}}</p>
              <p class="dev__title">Based in {{profile.location}}</p>
              <p class="dev__location">Experience: {{profile.experience}}</p>
              <ul class="dev__social">
                {% if social.social_github %}  
                <li>
                  <a title="Github" href="{{social.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
                {% if social.social_twitter %} 
                <li>
                  <a title="Twitter" href="{{social.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}
                {% if social.social_linkedin %} 
                <li>
                  <a title="LinkedIn" href="{{social.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}
                {% if social.social_website %} 
                <li>
                  <a title="Personal Website" href="{{social.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              {% if request.user.profile.id != profile.id  or not request.user.is_authenticated%}
              <a href="{% url 'create-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">{{profile.bio}}</p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Top Skills</h3>
            <div class="devInfo__skills">

            {% for  skill in skillsWithDesc %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">{{skill.description}}</p>
              </div>
            {% endfor %}
            

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">

                {% for  skill in skillsNoDesc %}   
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill.name}}</small>
                </span>
                {% endfor %}

              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
            {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{project.imageUrl}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">By {{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                        feedback out of {{project.total_votes}} vote{{project.total_votes|pluralize:"s"}}
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tag.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock content %}