api/urls.py
from django.urls import path
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns=[
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:pk>/', views.getSingleProject),
    path('projects/<str:pk>/vote/', views.projectVote),

    path('remove-tag/', views.removeTag),


]

cart/urls.py
from django.urls import path

from . import views

app_name='cart'

urlpatterns=[
    path('', views.cart_summaryView.as_view(), name='cart-summary'),
    path('add/', views.cart_addView.as_view(),  name='cart-add'),
    path('delete/', views.cart_deleteView.as_view(),  name='cart-delete'),
    path('update/', views.cart_updateView.as_view(),  name='cart-update')
]

templates/delete-template.html
{% extends 'main.html' %}

{% block content %}


<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <br>

            <form class="form" action="" method="POST">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{object}}"?</p>
                
                <a class="btn btn--sub btn--lg  my-md" href="{{request.GET.next}}">Cancel</a>

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Confirm" />
            </form>
        </div>
    </div>
</main>

{% endblock %}

templates/form-template.html
<!DOCTYPE html>
<html lang="en">


<body>

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
</body>

</html>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <!-- <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" /> -->
    
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    
    <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
    
    <link rel="stylesheet" href="{% static 'styles/app.css' %}" />
  
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>


    <script type="text/javascript">
        let user='{{request.user}}'

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                } 
            }
          return cookieValue;
        }
        // const csrftoken = getToken('csrftoken');
        const csrftoken = '{{ csrf_token }}';

        function getCookie(name){
            // Razdeluvanje na cookie stringot vo individualni name-value parovi vo array
            let cookieArr=document.cookie.split(";");

            for (let i = 0; i < cookieArr.length; i++) {
                let cookiePair=cookieArr[i].split("=");

                // Otstranuvanje na whitespace na pocetokot od cookie name i sporedba so daden string
                if(name == cookiePair[0].trim()){
                    return decodeURIComponent(cookiePair[1]);
                }
            }
            // vrati null ako ne e najdeno
            return null
        }

       
    </script>


    <title>ProfisSearch - Connect with Professionals!</title>
</head>
<body>
    {% include 'navbar.html' %}


    <div id="ajax_message">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}  fade show">
                    {{ message|safe }}
                </div>
            {% endfor %}
        {% endif %}
    </div>


    {% block content %}

    {% endblock content %}


    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="{% static 'uikit/app.js' %}"></script>


</body>

<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/cart.js' %}"></script>
</html>

templates/messages.html
{% for message in messages %}
<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
{% endfor %}

templates/navbar.html
{% load static %}
{% block content %}
<!-- Header Section -->
<header class="header">
  <div class="container container--narrow">
    
    <nav style="margin: auto;" class="header__nav">
      
      <input type="checkbox" id="responsive-menu" />
      <label for="responsive-menu" class="toggle-menu">
        <span>Menu</span>
        <div class="toggle-menu__lines"></div>
      </label>
      <ul class="header__menu">
        <li id="professionals" class="header__menuItem"><a href="{% url 'profiles' %}">Professionals</a></li>
        <li id="projects" class="header__menuItem"><a href="{% url 'projects' %}">Projects</a></li>
        <li id="merchandise" class="header__menuItem"><a href="{% url 'store' %}">Merchandise</a></li>
        
        {% if request.user.is_authenticated %}
          {% with total_qty=cart|length %}
          <li id="cart" class="header__menuItem"><a id="cart-qty" href="{% url 'cart:cart-summary' %}">
            
              Cart(<span id="navb-cart-qty">{{total_qty}}</span>)
            
          </a></li>
          {% endwith %}
        {% else %}
          <li id="cart" class="header__menuItem"><a id="cart-qty" href="{% url 'cart:cart-summary' %}">
            Cart
          </a></li>
        {% endif %}

        
        {% if request.user.is_authenticated %}

        {% if unreadCount > 0 %}
        <li id="inbox" class="header__menuItem"><a href="{% url 'inbox' %}">Inbox(<span>{{unreadCount}}</span>)</a></li>
        {% else %}
        <li id="inbox" class="header__menuItem"><a href="{% url 'inbox' %}">Inbox</a></li>
        {% endif %}

        <li id="account" class="header__menuItem"><a href="{% url 'account' %}">Account</a></li>
        
        <li class="header__menuItem"><a id="logBtn" href="{% url 'logout-user' %}" class="btn btn--sub">Logout</a></li>
        {% else %}
        
        <li class="header__menuItem"><a id="logBtn" href="{% url 'login-user' %}" class="btn btn--sub">Login/Sign Up</a></li>
        {% endif %}
      </ul>
    </nav>
  </div>
</header>

  {% endblock content %}

templates/pagination.html
{% if queryset.has_other_pages %}
<div class="pagination">
  <ul class="container">

    {% if queryset.has_previous %}
    <li><a  href="#" class="btn  paginate" 
           data-page="{{queryset.previous_page_number}}">&#10094; Prev</a></li>
    {% endif %}


    {% for page in custom_range %} 

    {% if page == queryset.number %}
    <li><a href="#" class="btn btn--sub paginate" data-page="{{page}}">{{page}}</a></li>
    {% else %}
      <li><a  href="#" class="btn paginate" data-page="{{page}}">{{page}}</a></li>
    {% endif %}
    {% endfor %}

    {% if queryset.has_next %}
    <li><a href="#" class="btn  paginate"
           data-page="{{queryset.next_page_number}}">Next &#10095;</a></li>
    {% endif %}


  </ul>
</div>
{% endif %}

templates/reset_confirm.html
{% extends 'main.html' %}


{% block content %}

<style>

input.input[type='text'],
input.input[type='email'],
input.input[type='password']
{
  min-width: 24rem;
  width: 100%;
  padding: 1.2rem 1.5rem;
  border-radius: 0.5rem;
  border: 2px solid var(--color-light);
  transition: all 0.3s ease-in-out;
  background-color: var(--color-bg);
}

input.input[type='text']:focus,
input.input[type='email']:focus,
input.input[type='password']:focus,
input.input[type='text']:active,
input.input[type='email']:active,
input.input[type='password']:active
{
  outline: none;
  border: 2px solid var(--color-main);
}

</style>

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Enter Password</h3>
            <P>Please enter your new password twice so we can verify you typed it correctly</p>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

templates/reset_password.html
{% extends 'main.html' %}


{% block content %}

<style>

input.input[type='text'],
input.input[type='email'],
input.input[type='password']
{
  min-width: 24rem;
  width: 100%;
  padding: 1.2rem 1.5rem;
  border-radius: 0.5rem;
  border: 2px solid var(--color-light);
  transition: all 0.3s ease-in-out;
  background-color: var(--color-bg);
}

input.input[type='text']:focus,
input.input[type='email']:focus,
input.input[type='password']:focus,
input.input[type='text']:active,
input.input[type='email']:active,
input.input[type='password']:active
{
  outline: none;
  border: 2px solid var(--color-main);
}

</style>

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Password reset</h3>
            <p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

templates/reset_password_conmplete.html
{% extends 'main.html' %}


{% block content %}


<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Password reset complete</h3>
            <p>Your password has been set. You may log in now.</p>
            <br>
            <a href="{% url 'login-user' %}"></a>
            
        </div>
    </div>
</main>

{% endblock content %}

templates/reset_password_sent.html
{% extends 'main.html' %}


{% block content %}


<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Password reset sent</h3>
            <p>We've emailed you instructions for setting your password, if an account
                exists with the email you entered. You should receive them shortly
            </p>
            <br>
            <p>If you don't receive an email, please make sure you've entered the email address you registered with.</p>
            
        </div>
    </div>
</main>

{% endblock content %}